name: Deploy Django project to SCW serverless containers

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Scaleway registry
        uses: docker/login-action@v2
        with:
          registry: rg.fr-par.scw.cloud/rfk-bgld
          username: nologin
          password: ${{ secrets.SCW_REGISTRY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rg.fr-par.scw.cloud/rfk-bgld/rfk-bildungsplattform:dev