# Generated by Django 4.2.4 on 2023-12-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchulungPage',
            new_name='Schulung',
        ),
        migrations.RenameModel(
            old_name='SchulungIndexPage',
            new_name='SchulungIndex',
        ),
        migrations.RenameField(
            model_name='schulungperson',
            old_name='schulungstermin',
            new_name='schulung',
        ),
    ]
