# Generated by Django 4.2.4 on 2023-08-26 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_funktion_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchulungsArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schulung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('art', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.schulungsart')),
            ],
        ),
        migrations.CreateModel(
            name='FunktionSchulung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervall', models.IntegerField()),
                ('funktion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.funktion')),
                ('schulung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.schulung')),
            ],
        ),
        migrations.CreateModel(
            name='Betrieb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inhaber', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.person')),
            ],
            options={
                'verbose_name_plural': 'betriebe',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='funktion',
            name='schulungsanforderung',
            field=models.ManyToManyField(through='core.FunktionSchulung', to='core.schulung'),
        ),
    ]
