# Generated by Django 4.2.4 on 2023-12-19 17:03

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_schulungpage_schulung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schulungperson',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='schulungperson',
            name='schulung',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='teilnehmer', to='core.schulung'),
        ),
    ]
