# Generated by Django 4.2.4 on 2023-09-21 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_schulungstermin_schulung"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="funktion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.funktion"
            ),
        ),
        migrations.CreateModel(
            name="SchulungsTerminPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.person"
                    ),
                ),
                (
                    "schulungstermin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.schulungstermin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teilnehmer",
                "verbose_name_plural": "Teilnehmer",
            },
        ),
    ]
