# Generated by Django 4.2.4 on 2023-09-22 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_person_funktion_schulungsterminperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schulungstermin',
            name='beschreibung',
        ),
        migrations.AddField(
            model_name='schulung',
            name='beschreibung',
            field=models.TextField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schulungsartfunktion',
            name='funktion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funktion'),
        ),
        migrations.AlterField(
            model_name='schulungsartfunktion',
            name='schulungsart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schulungsart'),
        ),
        migrations.AlterField(
            model_name='schulungsterminperson',
            name='status',
            field=models.CharField(choices=[('Angemeldet', 'Angemeldet'), ('Teilgenommen', 'Teilgenommen'), ('Entschuldigt', 'Entschuldigt'), ('Unentschuldigt', 'Unentschuldigt')], default='Angemeldet', max_length=50),
        ),
    ]
