# Generated by Django 4.2.4 on 2023-12-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_schulungpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schulungpage',
            name='type',
        ),
    ]
