# Generated by Django 4.2.4 on 2023-12-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_schulungpage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schulungsart',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
