# Generated by Django 5.0 on 2023-12-22 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_schulungstermin_ort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schulungstermin',
            name='ort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.schulungsort'),
        ),
    ]
