# Generated by Django 4.2.4 on 2023-12-09 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_schulungsart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schulungpage',
            name='art',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.schulungsart'),
        ),
    ]
