# Generated by Django 4.2.4 on 2023-12-09 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_schulungpage_art'),
    ]
