# Generated by Django 5.0 on 2023-12-22 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_schulungsort_adresse_schulungsort_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schulungsartfunktion',
            name='funktion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.funktion'),
        ),
        migrations.AlterField(
            model_name='schulungsartfunktion',
            name='schulungsart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.schulungsart'),
        ),
    ]
