# Generated by Django 5.0 on 2023-12-22 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_schulungsartfunktion_funktion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schulungsterminperson",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="core.person"
            ),
        ),
        migrations.AlterField(
            model_name="schulungsterminperson",
            name="schulungstermin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.schulungstermin",
            ),
        ),
    ]
