# Generated by Django 5.0 on 2023-12-27 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_schulungstermin_dauer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schulungstermin',
            old_name='datum',
            new_name='datum_von',
        ),
    ]
