# Generated by Django 5.0 on 2023-12-27 22:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_datum_schulungstermin_datum_von'),
    ]

    operations = [
        migrations.AddField(
            model_name='schulungstermin',
            name='datum_bis',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
