# Generated by Django 5.0 on 2023-12-30 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_betrieb_geschaeftsfuehrer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonBetrieb',
        ),
    ]
