# Generated by Django 5.0 on 2024-07-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='schulungsort',
            name='hinweise',
            field=models.TextField(blank=True, null=True),
        ),
    ]
