# Generated by Django 5.0 on 2024-07-05 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_schulung_preis_rabattiert_schulung_preis_standard"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SchulungsTerminPerson",
            new_name="SchulungsTeilnehmer",
        ),
        migrations.CreateModel(
            name="Bestellung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anzahl", models.IntegerField()),
                ("einzelpreis", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gesamtpreis", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("Bestellt", "Bestellt"), ("Storniert", "Storniert")],
                        default="Angemeldet",
                        max_length=50,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.person",
                    ),
                ),
                (
                    "schulungstermin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.schulungstermin",
                    ),
                ),
            ],
        ),
    ]
