# Generated by Django 5.0 on 2025-05-21 13:59

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=core.storage.ReplitObjectStorage, upload_to=''),
        ),
    ]
