# Generated by Django 5.2.1 on 2025-05-22 15:15

import core.models
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='allowed_funktionen',
            field=models.ManyToManyField(blank=True, help_text='Leer lassen um das Dokument für alle freizugeben', to='core.funktion'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=core.storage.ScalewayObjectStorage(), upload_to=core.models.get_unique_upload_path),
        ),
        migrations.AlterField(
            model_name='funktion',
            name='schulungsanforderung',
            field=models.ManyToManyField(through='core.SchulungsArtFunktion', through_fields=('funktion', 'schulungsart'), to='core.schulungsart'),
        ),
    ]
