# Generated by Django 5.0 on 2025-09-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_add_activation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="can_book_schulungen",
            field=models.BooleanField(
                default=True,
                help_text="Gibt an, ob diese Person Schulungen buchen darf",
                verbose_name="Darf Schulungen buchen",
            ),
        ),
    ]
