# Generated by Django 5.0 on 2025-09-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_person_can_book_schulungen"),
    ]

    operations = [
        migrations.AddField(
            model_name="bestellung",
            name="rechnungsadresse_name",
            field=models.CharField(
                blank=True,
                help_text="Name oder Firmenname für die Rechnung",
                max_length=200,
                null=True,
                verbose_name="Name/Firma",
            ),
        ),
        migrations.AddField(
            model_name="bestellung",
            name="rechnungsadresse_ort",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Ort"
            ),
        ),
        migrations.AddField(
            model_name="bestellung",
            name="rechnungsadresse_plz",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Postleitzahl"
            ),
        ),
        migrations.AddField(
            model_name="bestellung",
            name="rechnungsadresse_strasse",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Straße und Hausnummer",
            ),
        ),
    ]
