# Generated by Django 5.2.1 on 2025-10-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_activate_existing_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="adresse",
            field=models.CharField(
                blank=True,
                help_text="Straße und Hausnummer",
                max_length=200,
                null=True,
                verbose_name="Adresse",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="firmenanschrift",
            field=models.CharField(
                blank=True,
                help_text="Vollständige Adresse des Unternehmens",
                max_length=200,
                null=True,
                verbose_name="Firmenanschrift",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="firmenname",
            field=models.CharField(
                blank=True,
                help_text="Name des Unternehmens",
                max_length=200,
                null=True,
                verbose_name="Firmenname",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="ort",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Ort"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="plz",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Postleitzahl"
            ),
        ),
    ]
