# Generated by Django 4.2.4 on 2023-08-20 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="funktion",
            options={"ordering": ["name"], "verbose_name_plural": "funktionen"},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["nachname"], "verbose_name_plural": "personen"},
        ),
        migrations.AlterField(
            model_name="person",
            name="benutzer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
