# Generated by Django 4.2.4 on 2023-09-16 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_schulungsart_schulung_funktionschulung_betrieb_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchulungsArtFunktion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intervall", models.IntegerField()),
                (
                    "funktion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.funktion"
                    ),
                ),
                (
                    "schulungsart",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.schulungsart",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchulungsOrt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SchulungsTermin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateTimeField()),
                ("beschreibung", models.TextField(max_length=200)),
                (
                    "ort",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.schulungsort",
                    ),
                ),
                (
                    "schulung",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.schulung"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="FunktionSchulung",
        ),
        migrations.AlterField(
            model_name="funktion",
            name="schulungsanforderung",
            field=models.ManyToManyField(
                through="core.SchulungsArtFunktion", to="core.schulungsart"
            ),
        ),
    ]
