# Generated by Django 5.0 on 2024-02-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_alter_betrieb_geschaeftsfuehrer_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="funktion",
            options={"ordering": ["sortierung"], "verbose_name_plural": "funktionen"},
        ),
        migrations.AddField(
            model_name="funktion",
            name="sortierung",
            field=models.IntegerField(default=0),
        ),
    ]
