# Generated by Django 5.0 on 2024-04-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_alter_funktion_options_funktion_sortierung"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
