# Generated by Django 5.0 on 2024-07-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_schulungsort_hinweise"),
    ]

    operations = [
        migrations.AddField(
            model_name="schulung",
            name="preis_rabattiert",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="schulung",
            name="preis_standard",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
