name: Deploy Django project to SCW serverless containers

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Scaleway registry
        uses: docker/login-action@v2
        with:
          registry: rg.fr-par.scw.cloud/rfk-bgld
          username: nologin
          password: ${{ secrets.SCW_REGISTRY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rg.fr-par.scw.cloud/rfk-bgld/rfk-bildungsplattform:latest
          build-args: |
            PGDATABASE=${{ secrets.PGDATABASE }}
            PGHOST=${{ secrets.PGHOST }}
            PGUSER=${{ secrets.PGUSER }}  
            PGPORT=${{ secrets.PGPORT }}  
            PGPASSWORD=${{ secrets.PGPASSWORD }}

      - name: Trigger Serverless Container Redeployment
        env:
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
        run: |
          curl -X POST \
            -H "X-Auth-Token: $SCW_SECRET_KEY" \
            -H "Content-Type: application/json" \
            "https://api.scaleway.com/containers/v1beta1/regions/fr-par/containers/${{ secrets.SCW_CONTAINER_ID }}/deploy"
